//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BrickBot.BricksetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://brickset.com/api/", ConfigurationName="BricksetService.BricksetAPIv2Soap")]
    public interface BricksetAPIv2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getSets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.sets[] getSets(string apiKey, string userHash, string query, string theme, string subtheme, string setNumber, string year, string owned, string wanted, string orderBy, string pageSize, string pageNumber, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getSets", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.sets[]> getSetsAsync(string apiKey, string userHash, string query, string theme, string subtheme, string setNumber, string year, string owned, string wanted, string orderBy, string pageSize, string pageNumber, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.sets[] getSet(string apiKey, string userHash, string SetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getSet", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.sets[]> getSetAsync(string apiKey, string userHash, string SetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getRecentlyUpdatedSets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.sets[] getRecentlyUpdatedSets(string apiKey, int minutesAgo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getRecentlyUpdatedSets", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.sets[]> getRecentlyUpdatedSetsAsync(string apiKey, int minutesAgo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getAdditionalImages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.additionalImages[] getAdditionalImages(string apiKey, int setID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getAdditionalImages", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.additionalImages[]> getAdditionalImagesAsync(string apiKey, int setID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getReviews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.reviews[] getReviews(string apiKey, int setID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getReviews", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.reviews[]> getReviewsAsync(string apiKey, int setID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getInstructions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.instructions[] getInstructions(string apiKey, int setID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getInstructions", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.instructions[]> getInstructionsAsync(string apiKey, int setID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getMinifigCollection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.minifigCollection[] getMinifigCollection(string apiKey, string userHash, string query, string owned, string wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getMinifigCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.minifigCollection[]> getMinifigCollectionAsync(string apiKey, string userHash, string query, string owned, string wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getThemes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.themes[] getThemes(string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getThemes", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.themes[]> getThemesAsync(string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getSubthemes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.subthemes[] getSubthemes(string apiKey, string theme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getSubthemes", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.subthemes[]> getSubthemesAsync(string apiKey, string theme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getYears", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.years[] getYears(string apiKey, string theme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getYears", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.years[]> getYearsAsync(string apiKey, string theme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getThemesForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.themes[] getThemesForUser(string apiKey, string userHash, string owned, string wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getThemesForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.themes[]> getThemesForUserAsync(string apiKey, string userHash, string owned, string wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getSubthemesForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.subthemes[] getSubthemesForUser(string apiKey, string theme, string userHash, string owned, string wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getSubthemesForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.subthemes[]> getSubthemesForUserAsync(string apiKey, string theme, string userHash, string owned, string wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getYearsForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.years[] getYearsForUser(string apiKey, string theme, string userHash, string owned, string wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getYearsForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.years[]> getYearsForUserAsync(string apiKey, string theme, string userHash, string owned, string wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getUserNotes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.userNotes[] getUserNotes(string apiKey, string userHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getUserNotes", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.userNotes[]> getUserNotesAsync(string apiKey, string userHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getCollectionTotals", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.collectionTotals getCollectionTotals(string apiKey, string userHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getCollectionTotals", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.collectionTotals> getCollectionTotalsAsync(string apiKey, string userHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setCollection(string apiKey, string userHash, int setID, int qtyOwned, int wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setCollectionAsync(string apiKey, string userHash, int setID, int qtyOwned, int wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection_owns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setCollection_owns(string apiKey, string userHash, int setID, int owned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection_owns", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setCollection_ownsAsync(string apiKey, string userHash, int setID, int owned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection_wants", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setCollection_wants(string apiKey, string userHash, int setID, int wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection_wants", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setCollection_wantsAsync(string apiKey, string userHash, int setID, int wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection_userNotes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setCollection_userNotes(string apiKey, string userHash, int setID, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection_userNotes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setCollection_userNotesAsync(string apiKey, string userHash, int setID, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection_qtyOwned", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setCollection_qtyOwned(string apiKey, string userHash, int setID, int qtyOwned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollection_qtyOwned", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setCollection_qtyOwnedAsync(string apiKey, string userHash, int setID, int qtyOwned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setMinifigCollection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setMinifigCollection(string apiKey, string userHash, string minifigNumber, int qtyOwned, int wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setMinifigCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setMinifigCollectionAsync(string apiKey, string userHash, string minifigNumber, int qtyOwned, int wanted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string login(string apiKey, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> loginAsync(string apiKey, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollectionDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setCollectionDetail(string apiKey, string userHash, BrickBot.BricksetService.collectionDetails detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/setCollectionDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setCollectionDetailAsync(string apiKey, string userHash, BrickBot.BricksetService.collectionDetails detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getCollectionDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.collectionDetails[] getCollectionDetail(string apiKey, string userHash, string SetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getCollectionDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.collectionDetails[]> getCollectionDetailAsync(string apiKey, string userHash, string SetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getCollectionDetailConditions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrickBot.BricksetService.conditions[] getCollectionDetailConditions(string apiKey, string which);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/getCollectionDetailConditions", ReplyAction="*")]
        System.Threading.Tasks.Task<BrickBot.BricksetService.conditions[]> getCollectionDetailConditionsAsync(string apiKey, string which);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/checkKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string checkKey(string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/checkKey", ReplyAction="*")]
        System.Threading.Tasks.Task<string> checkKeyAsync(string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/checkUserHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string checkUserHash(string userHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brickset.com/api/checkUserHash", ReplyAction="*")]
        System.Threading.Tasks.Task<string> checkUserHashAsync(string userHash);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class sets : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int setIDField;
        
        private string numberField;
        
        private int numberVariantField;
        
        private string nameField;
        
        private string yearField;
        
        private string themeField;
        
        private string themeGroupField;
        
        private string subthemeField;
        
        private string piecesField;
        
        private string minifigsField;
        
        private bool imageField;
        
        private string imageFilenameField;
        
        private string thumbnailURLField;
        
        private string largeThumbnailURLField;
        
        private string imageURLField;
        
        private string bricksetURLField;
        
        private bool releasedField;
        
        private bool ownedField;
        
        private bool wantedField;
        
        private int qtyOwnedField;
        
        private string userNotesField;
        
        private int aCMDataCountField;
        
        private int ownedByTotalField;
        
        private int wantedByTotalField;
        
        private string uKRetailPriceField;
        
        private string uSRetailPriceField;
        
        private string cARetailPriceField;
        
        private string eURetailPriceField;
        
        private string uSDateAddedToSAHField;
        
        private string uSDateRemovedFromSAHField;
        
        private decimal ratingField;
        
        private int reviewCountField;
        
        private string packagingTypeField;
        
        private string availabilityField;
        
        private int instructionsCountField;
        
        private int additionalImageCountField;
        
        private string eANField;
        
        private string uPCField;
        
        private string descriptionField;
        
        private System.DateTime lastUpdatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int setID {
            get {
                return this.setIDField;
            }
            set {
                this.setIDField = value;
                this.RaisePropertyChanged("setID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int numberVariant {
            get {
                return this.numberVariantField;
            }
            set {
                this.numberVariantField = value;
                this.RaisePropertyChanged("numberVariant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string theme {
            get {
                return this.themeField;
            }
            set {
                this.themeField = value;
                this.RaisePropertyChanged("theme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string themeGroup {
            get {
                return this.themeGroupField;
            }
            set {
                this.themeGroupField = value;
                this.RaisePropertyChanged("themeGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string subtheme {
            get {
                return this.subthemeField;
            }
            set {
                this.subthemeField = value;
                this.RaisePropertyChanged("subtheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
                this.RaisePropertyChanged("pieces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string minifigs {
            get {
                return this.minifigsField;
            }
            set {
                this.minifigsField = value;
                this.RaisePropertyChanged("minifigs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string imageFilename {
            get {
                return this.imageFilenameField;
            }
            set {
                this.imageFilenameField = value;
                this.RaisePropertyChanged("imageFilename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string thumbnailURL {
            get {
                return this.thumbnailURLField;
            }
            set {
                this.thumbnailURLField = value;
                this.RaisePropertyChanged("thumbnailURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string largeThumbnailURL {
            get {
                return this.largeThumbnailURLField;
            }
            set {
                this.largeThumbnailURLField = value;
                this.RaisePropertyChanged("largeThumbnailURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string imageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
                this.RaisePropertyChanged("imageURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string bricksetURL {
            get {
                return this.bricksetURLField;
            }
            set {
                this.bricksetURLField = value;
                this.RaisePropertyChanged("bricksetURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool released {
            get {
                return this.releasedField;
            }
            set {
                this.releasedField = value;
                this.RaisePropertyChanged("released");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool owned {
            get {
                return this.ownedField;
            }
            set {
                this.ownedField = value;
                this.RaisePropertyChanged("owned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool wanted {
            get {
                return this.wantedField;
            }
            set {
                this.wantedField = value;
                this.RaisePropertyChanged("wanted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int qtyOwned {
            get {
                return this.qtyOwnedField;
            }
            set {
                this.qtyOwnedField = value;
                this.RaisePropertyChanged("qtyOwned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string userNotes {
            get {
                return this.userNotesField;
            }
            set {
                this.userNotesField = value;
                this.RaisePropertyChanged("userNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int ACMDataCount {
            get {
                return this.aCMDataCountField;
            }
            set {
                this.aCMDataCountField = value;
                this.RaisePropertyChanged("ACMDataCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int ownedByTotal {
            get {
                return this.ownedByTotalField;
            }
            set {
                this.ownedByTotalField = value;
                this.RaisePropertyChanged("ownedByTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int wantedByTotal {
            get {
                return this.wantedByTotalField;
            }
            set {
                this.wantedByTotalField = value;
                this.RaisePropertyChanged("wantedByTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string UKRetailPrice {
            get {
                return this.uKRetailPriceField;
            }
            set {
                this.uKRetailPriceField = value;
                this.RaisePropertyChanged("UKRetailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string USRetailPrice {
            get {
                return this.uSRetailPriceField;
            }
            set {
                this.uSRetailPriceField = value;
                this.RaisePropertyChanged("USRetailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CARetailPrice {
            get {
                return this.cARetailPriceField;
            }
            set {
                this.cARetailPriceField = value;
                this.RaisePropertyChanged("CARetailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string EURetailPrice {
            get {
                return this.eURetailPriceField;
            }
            set {
                this.eURetailPriceField = value;
                this.RaisePropertyChanged("EURetailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string USDateAddedToSAH {
            get {
                return this.uSDateAddedToSAHField;
            }
            set {
                this.uSDateAddedToSAHField = value;
                this.RaisePropertyChanged("USDateAddedToSAH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string USDateRemovedFromSAH {
            get {
                return this.uSDateRemovedFromSAHField;
            }
            set {
                this.uSDateRemovedFromSAHField = value;
                this.RaisePropertyChanged("USDateRemovedFromSAH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
                this.RaisePropertyChanged("rating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public int reviewCount {
            get {
                return this.reviewCountField;
            }
            set {
                this.reviewCountField = value;
                this.RaisePropertyChanged("reviewCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string packagingType {
            get {
                return this.packagingTypeField;
            }
            set {
                this.packagingTypeField = value;
                this.RaisePropertyChanged("packagingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
                this.RaisePropertyChanged("availability");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public int instructionsCount {
            get {
                return this.instructionsCountField;
            }
            set {
                this.instructionsCountField = value;
                this.RaisePropertyChanged("instructionsCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public int additionalImageCount {
            get {
                return this.additionalImageCountField;
            }
            set {
                this.additionalImageCountField = value;
                this.RaisePropertyChanged("additionalImageCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string EAN {
            get {
                return this.eANField;
            }
            set {
                this.eANField = value;
                this.RaisePropertyChanged("EAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string UPC {
            get {
                return this.uPCField;
            }
            set {
                this.uPCField = value;
                this.RaisePropertyChanged("UPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public System.DateTime lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
                this.RaisePropertyChanged("lastUpdated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class conditions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
                this.RaisePropertyChanged("condition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class collectionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int collectionIDField;
        
        private string dateAcquiredField;
        
        private string currencyField;
        
        private decimal pricePaidField;
        
        private decimal additionalPricePaidField;
        
        private decimal currentEstimatedValueField;
        
        private string conditionWhenAcquiredField;
        
        private string acquiredFromField;
        
        private string conditionNowField;
        
        private string locationField;
        
        private string notesField;
        
        private bool partsField;
        
        private bool minifigsField;
        
        private bool instructionsField;
        
        private bool boxField;
        
        private bool willTradeField;
        
        private bool modifiedField;
        
        private bool deletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int collectionID {
            get {
                return this.collectionIDField;
            }
            set {
                this.collectionIDField = value;
                this.RaisePropertyChanged("collectionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dateAcquired {
            get {
                return this.dateAcquiredField;
            }
            set {
                this.dateAcquiredField = value;
                this.RaisePropertyChanged("dateAcquired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal pricePaid {
            get {
                return this.pricePaidField;
            }
            set {
                this.pricePaidField = value;
                this.RaisePropertyChanged("pricePaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal additionalPricePaid {
            get {
                return this.additionalPricePaidField;
            }
            set {
                this.additionalPricePaidField = value;
                this.RaisePropertyChanged("additionalPricePaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal currentEstimatedValue {
            get {
                return this.currentEstimatedValueField;
            }
            set {
                this.currentEstimatedValueField = value;
                this.RaisePropertyChanged("currentEstimatedValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string conditionWhenAcquired {
            get {
                return this.conditionWhenAcquiredField;
            }
            set {
                this.conditionWhenAcquiredField = value;
                this.RaisePropertyChanged("conditionWhenAcquired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string acquiredFrom {
            get {
                return this.acquiredFromField;
            }
            set {
                this.acquiredFromField = value;
                this.RaisePropertyChanged("acquiredFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string conditionNow {
            get {
                return this.conditionNowField;
            }
            set {
                this.conditionNowField = value;
                this.RaisePropertyChanged("conditionNow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool minifigs {
            get {
                return this.minifigsField;
            }
            set {
                this.minifigsField = value;
                this.RaisePropertyChanged("minifigs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool instructions {
            get {
                return this.instructionsField;
            }
            set {
                this.instructionsField = value;
                this.RaisePropertyChanged("instructions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool box {
            get {
                return this.boxField;
            }
            set {
                this.boxField = value;
                this.RaisePropertyChanged("box");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool willTrade {
            get {
                return this.willTradeField;
            }
            set {
                this.willTradeField = value;
                this.RaisePropertyChanged("willTrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("deleted");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class collectionTotals : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalSetsOwnedField;
        
        private int totalDistinctSetsOwnedField;
        
        private int totalSetsWantedField;
        
        private int totalMinifigsOwnedField;
        
        private int totalMinifigsWantedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int totalSetsOwned {
            get {
                return this.totalSetsOwnedField;
            }
            set {
                this.totalSetsOwnedField = value;
                this.RaisePropertyChanged("totalSetsOwned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int totalDistinctSetsOwned {
            get {
                return this.totalDistinctSetsOwnedField;
            }
            set {
                this.totalDistinctSetsOwnedField = value;
                this.RaisePropertyChanged("totalDistinctSetsOwned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int totalSetsWanted {
            get {
                return this.totalSetsWantedField;
            }
            set {
                this.totalSetsWantedField = value;
                this.RaisePropertyChanged("totalSetsWanted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int totalMinifigsOwned {
            get {
                return this.totalMinifigsOwnedField;
            }
            set {
                this.totalMinifigsOwnedField = value;
                this.RaisePropertyChanged("totalMinifigsOwned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int totalMinifigsWanted {
            get {
                return this.totalMinifigsWantedField;
            }
            set {
                this.totalMinifigsWantedField = value;
                this.RaisePropertyChanged("totalMinifigsWanted");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class userNotes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int setIDField;
        
        private string userNotes1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int setID {
            get {
                return this.setIDField;
            }
            set {
                this.setIDField = value;
                this.RaisePropertyChanged("setID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userNotes", Order=1)]
        public string userNotes1 {
            get {
                return this.userNotes1Field;
            }
            set {
                this.userNotes1Field = value;
                this.RaisePropertyChanged("userNotes1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class years : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string themeField;
        
        private string yearField;
        
        private int setCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string theme {
            get {
                return this.themeField;
            }
            set {
                this.themeField = value;
                this.RaisePropertyChanged("theme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int setCount {
            get {
                return this.setCountField;
            }
            set {
                this.setCountField = value;
                this.RaisePropertyChanged("setCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class subthemes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string themeField;
        
        private string subthemeField;
        
        private int setCountField;
        
        private int yearFromField;
        
        private int yearToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string theme {
            get {
                return this.themeField;
            }
            set {
                this.themeField = value;
                this.RaisePropertyChanged("theme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string subtheme {
            get {
                return this.subthemeField;
            }
            set {
                this.subthemeField = value;
                this.RaisePropertyChanged("subtheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int setCount {
            get {
                return this.setCountField;
            }
            set {
                this.setCountField = value;
                this.RaisePropertyChanged("setCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int yearFrom {
            get {
                return this.yearFromField;
            }
            set {
                this.yearFromField = value;
                this.RaisePropertyChanged("yearFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int yearTo {
            get {
                return this.yearToField;
            }
            set {
                this.yearToField = value;
                this.RaisePropertyChanged("yearTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class themes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string themeField;
        
        private int setCountField;
        
        private int subthemeCountField;
        
        private int yearFromField;
        
        private int yearToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string theme {
            get {
                return this.themeField;
            }
            set {
                this.themeField = value;
                this.RaisePropertyChanged("theme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int setCount {
            get {
                return this.setCountField;
            }
            set {
                this.setCountField = value;
                this.RaisePropertyChanged("setCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int subthemeCount {
            get {
                return this.subthemeCountField;
            }
            set {
                this.subthemeCountField = value;
                this.RaisePropertyChanged("subthemeCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int yearFrom {
            get {
                return this.yearFromField;
            }
            set {
                this.yearFromField = value;
                this.RaisePropertyChanged("yearFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int yearTo {
            get {
                return this.yearToField;
            }
            set {
                this.yearToField = value;
                this.RaisePropertyChanged("yearTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class minifigCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string minifigNumberField;
        
        private int ownedInSetsField;
        
        private int ownedLooseField;
        
        private int ownedTotalField;
        
        private bool wantedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string minifigNumber {
            get {
                return this.minifigNumberField;
            }
            set {
                this.minifigNumberField = value;
                this.RaisePropertyChanged("minifigNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ownedInSets {
            get {
                return this.ownedInSetsField;
            }
            set {
                this.ownedInSetsField = value;
                this.RaisePropertyChanged("ownedInSets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ownedLoose {
            get {
                return this.ownedLooseField;
            }
            set {
                this.ownedLooseField = value;
                this.RaisePropertyChanged("ownedLoose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ownedTotal {
            get {
                return this.ownedTotalField;
            }
            set {
                this.ownedTotalField = value;
                this.RaisePropertyChanged("ownedTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool wanted {
            get {
                return this.wantedField;
            }
            set {
                this.wantedField = value;
                this.RaisePropertyChanged("wanted");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class instructions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uRLField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class reviews : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorField;
        
        private System.DateTime datePostedField;
        
        private int overallRatingField;
        
        private int partsField;
        
        private int buildingExperienceField;
        
        private int playabilityField;
        
        private int valueForMoneyField;
        
        private string titleField;
        
        private string reviewField;
        
        private bool hTMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime datePosted {
            get {
                return this.datePostedField;
            }
            set {
                this.datePostedField = value;
                this.RaisePropertyChanged("datePosted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int overallRating {
            get {
                return this.overallRatingField;
            }
            set {
                this.overallRatingField = value;
                this.RaisePropertyChanged("overallRating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int buildingExperience {
            get {
                return this.buildingExperienceField;
            }
            set {
                this.buildingExperienceField = value;
                this.RaisePropertyChanged("buildingExperience");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int playability {
            get {
                return this.playabilityField;
            }
            set {
                this.playabilityField = value;
                this.RaisePropertyChanged("playability");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int valueForMoney {
            get {
                return this.valueForMoneyField;
            }
            set {
                this.valueForMoneyField = value;
                this.RaisePropertyChanged("valueForMoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string review {
            get {
                return this.reviewField;
            }
            set {
                this.reviewField = value;
                this.RaisePropertyChanged("review");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool HTML {
            get {
                return this.hTMLField;
            }
            set {
                this.hTMLField = value;
                this.RaisePropertyChanged("HTML");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brickset.com/api/")]
    public partial class additionalImages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string thumbnailURLField;
        
        private string largeThumbnailURLField;
        
        private string imageURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string thumbnailURL {
            get {
                return this.thumbnailURLField;
            }
            set {
                this.thumbnailURLField = value;
                this.RaisePropertyChanged("thumbnailURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string largeThumbnailURL {
            get {
                return this.largeThumbnailURLField;
            }
            set {
                this.largeThumbnailURLField = value;
                this.RaisePropertyChanged("largeThumbnailURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string imageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
                this.RaisePropertyChanged("imageURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BricksetAPIv2SoapChannel : BrickBot.BricksetService.BricksetAPIv2Soap, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BricksetAPIv2SoapClient : System.ServiceModel.ClientBase<BrickBot.BricksetService.BricksetAPIv2Soap>, BrickBot.BricksetService.BricksetAPIv2Soap {
        
        public BricksetAPIv2SoapClient() {
        }
        
        public BricksetAPIv2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BricksetAPIv2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BricksetAPIv2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BricksetAPIv2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BrickBot.BricksetService.sets[] getSets(string apiKey, string userHash, string query, string theme, string subtheme, string setNumber, string year, string owned, string wanted, string orderBy, string pageSize, string pageNumber, string userName) {
            return base.Channel.getSets(apiKey, userHash, query, theme, subtheme, setNumber, year, owned, wanted, orderBy, pageSize, pageNumber, userName);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.sets[]> getSetsAsync(string apiKey, string userHash, string query, string theme, string subtheme, string setNumber, string year, string owned, string wanted, string orderBy, string pageSize, string pageNumber, string userName) {
            return base.Channel.getSetsAsync(apiKey, userHash, query, theme, subtheme, setNumber, year, owned, wanted, orderBy, pageSize, pageNumber, userName);
        }
        
        public BrickBot.BricksetService.sets[] getSet(string apiKey, string userHash, string SetID) {
            return base.Channel.getSet(apiKey, userHash, SetID);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.sets[]> getSetAsync(string apiKey, string userHash, string SetID) {
            return base.Channel.getSetAsync(apiKey, userHash, SetID);
        }
        
        public BrickBot.BricksetService.sets[] getRecentlyUpdatedSets(string apiKey, int minutesAgo) {
            return base.Channel.getRecentlyUpdatedSets(apiKey, minutesAgo);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.sets[]> getRecentlyUpdatedSetsAsync(string apiKey, int minutesAgo) {
            return base.Channel.getRecentlyUpdatedSetsAsync(apiKey, minutesAgo);
        }
        
        public BrickBot.BricksetService.additionalImages[] getAdditionalImages(string apiKey, int setID) {
            return base.Channel.getAdditionalImages(apiKey, setID);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.additionalImages[]> getAdditionalImagesAsync(string apiKey, int setID) {
            return base.Channel.getAdditionalImagesAsync(apiKey, setID);
        }
        
        public BrickBot.BricksetService.reviews[] getReviews(string apiKey, int setID) {
            return base.Channel.getReviews(apiKey, setID);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.reviews[]> getReviewsAsync(string apiKey, int setID) {
            return base.Channel.getReviewsAsync(apiKey, setID);
        }
        
        public BrickBot.BricksetService.instructions[] getInstructions(string apiKey, int setID) {
            return base.Channel.getInstructions(apiKey, setID);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.instructions[]> getInstructionsAsync(string apiKey, int setID) {
            return base.Channel.getInstructionsAsync(apiKey, setID);
        }
        
        public BrickBot.BricksetService.minifigCollection[] getMinifigCollection(string apiKey, string userHash, string query, string owned, string wanted) {
            return base.Channel.getMinifigCollection(apiKey, userHash, query, owned, wanted);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.minifigCollection[]> getMinifigCollectionAsync(string apiKey, string userHash, string query, string owned, string wanted) {
            return base.Channel.getMinifigCollectionAsync(apiKey, userHash, query, owned, wanted);
        }
        
        public BrickBot.BricksetService.themes[] getThemes(string apiKey) {
            return base.Channel.getThemes(apiKey);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.themes[]> getThemesAsync(string apiKey) {
            return base.Channel.getThemesAsync(apiKey);
        }
        
        public BrickBot.BricksetService.subthemes[] getSubthemes(string apiKey, string theme) {
            return base.Channel.getSubthemes(apiKey, theme);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.subthemes[]> getSubthemesAsync(string apiKey, string theme) {
            return base.Channel.getSubthemesAsync(apiKey, theme);
        }
        
        public BrickBot.BricksetService.years[] getYears(string apiKey, string theme) {
            return base.Channel.getYears(apiKey, theme);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.years[]> getYearsAsync(string apiKey, string theme) {
            return base.Channel.getYearsAsync(apiKey, theme);
        }
        
        public BrickBot.BricksetService.themes[] getThemesForUser(string apiKey, string userHash, string owned, string wanted) {
            return base.Channel.getThemesForUser(apiKey, userHash, owned, wanted);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.themes[]> getThemesForUserAsync(string apiKey, string userHash, string owned, string wanted) {
            return base.Channel.getThemesForUserAsync(apiKey, userHash, owned, wanted);
        }
        
        public BrickBot.BricksetService.subthemes[] getSubthemesForUser(string apiKey, string theme, string userHash, string owned, string wanted) {
            return base.Channel.getSubthemesForUser(apiKey, theme, userHash, owned, wanted);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.subthemes[]> getSubthemesForUserAsync(string apiKey, string theme, string userHash, string owned, string wanted) {
            return base.Channel.getSubthemesForUserAsync(apiKey, theme, userHash, owned, wanted);
        }
        
        public BrickBot.BricksetService.years[] getYearsForUser(string apiKey, string theme, string userHash, string owned, string wanted) {
            return base.Channel.getYearsForUser(apiKey, theme, userHash, owned, wanted);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.years[]> getYearsForUserAsync(string apiKey, string theme, string userHash, string owned, string wanted) {
            return base.Channel.getYearsForUserAsync(apiKey, theme, userHash, owned, wanted);
        }
        
        public BrickBot.BricksetService.userNotes[] getUserNotes(string apiKey, string userHash) {
            return base.Channel.getUserNotes(apiKey, userHash);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.userNotes[]> getUserNotesAsync(string apiKey, string userHash) {
            return base.Channel.getUserNotesAsync(apiKey, userHash);
        }
        
        public BrickBot.BricksetService.collectionTotals getCollectionTotals(string apiKey, string userHash) {
            return base.Channel.getCollectionTotals(apiKey, userHash);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.collectionTotals> getCollectionTotalsAsync(string apiKey, string userHash) {
            return base.Channel.getCollectionTotalsAsync(apiKey, userHash);
        }
        
        public string setCollection(string apiKey, string userHash, int setID, int qtyOwned, int wanted) {
            return base.Channel.setCollection(apiKey, userHash, setID, qtyOwned, wanted);
        }
        
        public System.Threading.Tasks.Task<string> setCollectionAsync(string apiKey, string userHash, int setID, int qtyOwned, int wanted) {
            return base.Channel.setCollectionAsync(apiKey, userHash, setID, qtyOwned, wanted);
        }
        
        public string setCollection_owns(string apiKey, string userHash, int setID, int owned) {
            return base.Channel.setCollection_owns(apiKey, userHash, setID, owned);
        }
        
        public System.Threading.Tasks.Task<string> setCollection_ownsAsync(string apiKey, string userHash, int setID, int owned) {
            return base.Channel.setCollection_ownsAsync(apiKey, userHash, setID, owned);
        }
        
        public string setCollection_wants(string apiKey, string userHash, int setID, int wanted) {
            return base.Channel.setCollection_wants(apiKey, userHash, setID, wanted);
        }
        
        public System.Threading.Tasks.Task<string> setCollection_wantsAsync(string apiKey, string userHash, int setID, int wanted) {
            return base.Channel.setCollection_wantsAsync(apiKey, userHash, setID, wanted);
        }
        
        public string setCollection_userNotes(string apiKey, string userHash, int setID, string notes) {
            return base.Channel.setCollection_userNotes(apiKey, userHash, setID, notes);
        }
        
        public System.Threading.Tasks.Task<string> setCollection_userNotesAsync(string apiKey, string userHash, int setID, string notes) {
            return base.Channel.setCollection_userNotesAsync(apiKey, userHash, setID, notes);
        }
        
        public string setCollection_qtyOwned(string apiKey, string userHash, int setID, int qtyOwned) {
            return base.Channel.setCollection_qtyOwned(apiKey, userHash, setID, qtyOwned);
        }
        
        public System.Threading.Tasks.Task<string> setCollection_qtyOwnedAsync(string apiKey, string userHash, int setID, int qtyOwned) {
            return base.Channel.setCollection_qtyOwnedAsync(apiKey, userHash, setID, qtyOwned);
        }
        
        public string setMinifigCollection(string apiKey, string userHash, string minifigNumber, int qtyOwned, int wanted) {
            return base.Channel.setMinifigCollection(apiKey, userHash, minifigNumber, qtyOwned, wanted);
        }
        
        public System.Threading.Tasks.Task<string> setMinifigCollectionAsync(string apiKey, string userHash, string minifigNumber, int qtyOwned, int wanted) {
            return base.Channel.setMinifigCollectionAsync(apiKey, userHash, minifigNumber, qtyOwned, wanted);
        }
        
        public string login(string apiKey, string username, string password) {
            return base.Channel.login(apiKey, username, password);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string apiKey, string username, string password) {
            return base.Channel.loginAsync(apiKey, username, password);
        }
        
        public string setCollectionDetail(string apiKey, string userHash, BrickBot.BricksetService.collectionDetails detail) {
            return base.Channel.setCollectionDetail(apiKey, userHash, detail);
        }
        
        public System.Threading.Tasks.Task<string> setCollectionDetailAsync(string apiKey, string userHash, BrickBot.BricksetService.collectionDetails detail) {
            return base.Channel.setCollectionDetailAsync(apiKey, userHash, detail);
        }
        
        public BrickBot.BricksetService.collectionDetails[] getCollectionDetail(string apiKey, string userHash, string SetID) {
            return base.Channel.getCollectionDetail(apiKey, userHash, SetID);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.collectionDetails[]> getCollectionDetailAsync(string apiKey, string userHash, string SetID) {
            return base.Channel.getCollectionDetailAsync(apiKey, userHash, SetID);
        }
        
        public BrickBot.BricksetService.conditions[] getCollectionDetailConditions(string apiKey, string which) {
            return base.Channel.getCollectionDetailConditions(apiKey, which);
        }
        
        public System.Threading.Tasks.Task<BrickBot.BricksetService.conditions[]> getCollectionDetailConditionsAsync(string apiKey, string which) {
            return base.Channel.getCollectionDetailConditionsAsync(apiKey, which);
        }
        
        public string checkKey(string apiKey) {
            return base.Channel.checkKey(apiKey);
        }
        
        public System.Threading.Tasks.Task<string> checkKeyAsync(string apiKey) {
            return base.Channel.checkKeyAsync(apiKey);
        }
        
        public string checkUserHash(string userHash) {
            return base.Channel.checkUserHash(userHash);
        }
        
        public System.Threading.Tasks.Task<string> checkUserHashAsync(string userHash) {
            return base.Channel.checkUserHashAsync(userHash);
        }
    }
}
