//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BrickBotRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrickBotRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBot.Properties.BrickBotRes", typeof(BrickBotRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string AllInstructions {
            get {
                return ResourceManager.GetString("AllInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string AllSet {
            get {
                return ResourceManager.GetString("AllSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give me the book number.
        /// </summary>
        internal static string BookNumber {
            get {
                return ResourceManager.GetString("BookNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick brack broke, looks like something broke..
        /// </summary>
        internal static string BrickBotError {
            get {
                return ResourceManager.GetString("BrickBotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string BricklinkBook {
            get {
                return ResourceManager.GetString("BricklinkBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minifig.
        /// </summary>
        internal static string BricklinkMinifig {
            get {
                return ResourceManager.GetString("BricklinkMinifig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string BricklinkPart {
            get {
                return ResourceManager.GetString("BricklinkPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string BricklinkSet {
            get {
                return ResourceManager.GetString("BricklinkSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string BricksetInstructions {
            get {
                return ResourceManager.GetString("BricksetInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string BricksetSet {
            get {
                return ResourceManager.GetString("BricksetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give me your prefered currency..
        /// </summary>
        internal static string CurrencyGiveMeCurrency {
            get {
                return ResourceManager.GetString("CurrencyGiveMeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for setting your currency. Please note that so far in this beta version, all is in $..
        /// </summary>
        internal static string CurrencyThankYou {
            get {
                return ResourceManager.GetString("CurrencyThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usercurrency.
        /// </summary>
        internal static string CurrencyValue {
            get {
                return ResourceManager.GetString("CurrencyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give me the set number for instructions .
        /// </summary>
        internal static string InstructionsNumber {
            get {
                return ResourceManager.GetString("InstructionsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give me the minifig number.
        /// </summary>
        internal static string MinifigNumber {
            get {
                return ResourceManager.GetString("MinifigNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give me the MOC number.
        /// </summary>
        internal static string MocNumber {
            get {
                return ResourceManager.GetString("MocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give me the part number.
        /// </summary>
        internal static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string PeeronInstructions {
            get {
                return ResourceManager.GetString("PeeronInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string PeeronSet {
            get {
                return ResourceManager.GetString("PeeronSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        internal static string RebrickableMoc {
            get {
                return ResourceManager.GetString("RebrickableMoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string RebrickablePart {
            get {
                return ResourceManager.GetString("RebrickablePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string RebrickableSet {
            get {
                return ResourceManager.GetString("RebrickableSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick broke, can&apos;t find what you&apos;re looking for. Please try again maybe with another number!.
        /// </summary>
        internal static string SearchError {
            get {
                return ResourceManager.GetString("SearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give me the set number.
        /// </summary>
        internal static string SetNumber {
            get {
                return ResourceManager.GetString("SetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Please give me couple of seconds to get your information..
        /// </summary>
        internal static string ThanksGiveMeASec {
            get {
                return ResourceManager.GetString("ThanksGiveMeASec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string WelcomeAll {
            get {
                return ResourceManager.GetString("WelcomeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bricklink.
        /// </summary>
        internal static string WelcomeBricklink {
            get {
                return ResourceManager.GetString("WelcomeBricklink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brickset.
        /// </summary>
        internal static string WelcomeBrickset {
            get {
                return ResourceManager.GetString("WelcomeBrickset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peeron.
        /// </summary>
        internal static string WelcomePeeron {
            get {
                return ResourceManager.GetString("WelcomePeeron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebrickable.
        /// </summary>
        internal static string WelcomeRebrickable {
            get {
                return ResourceManager.GetString("WelcomeRebrickable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set currency (default $).
        /// </summary>
        internal static string WelcomeSetCurrency {
            get {
                return ResourceManager.GetString("WelcomeSetCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whatsearchfor.
        /// </summary>
        internal static string WhatSearFor {
            get {
                return ResourceManager.GetString("WhatSearFor", resourceCulture);
            }
        }
    }
}
